import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Import the global styles
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";
import { WhyChooseUs } from "../components/WhyChooseUs";

// Import the fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the page
export const metadata = {
  title: "SA Windows & Doors Repair Services",
  description: "Generated by create next app",
};

// RootLayout function rendering the overall layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
  
        <Footer />
      </body>
    </html>
  );
}
